export const menuConfig = [
	{
		label: 'Portfolio',
		path: 'portfolio',
		isDetail: false,
		children: [
			{ label: 'Slough', id: 1, path: 'pic/work-pic.jpg' },
			{
				label: '此方',
				id: 2,
				path: 'pic/work-pic.jpg',
				info: 'Leg<br/>Cyanotypeonwatercolorpaper<br/>(297cmx420cm)',
				description:
					'ある日、朝起床したら、不意にシーツがくしゃくしゃになっていることに気が付いた｡そこには無意識のうちに自分の痕跡が残されていた｡この過ぎ去った時間で無意識下の自分が現れたと思う｡そもそもの本来の私はいつ頃から現れ始め、どんな姿をしていたのか、そしてこれからどんな姿になっていくのだろうか…考えが止まらない｡本来の私を探究するために、私はこのプロジェクトを始めた｡サイアノタイプを使ったのは、精密に複写できる写真の古典技法だから。カメラを介さず、最もストレートに表現できる｡撮られたのは私自身と同世代の人たちだ｡一人でネガの上に横たわると、最初は意識が鮮明に働いていたが、時間が経つにつれて、無意識の領域に入る｡そして、再び意識へと戻る。そうした時間のプロセスが痕跡としてネガに残った｡　体は現実の世界でのできことに反応する。私たちの身体はこの世界を体験し、身体の感覚シ-----ある日、朝起床したら、不意にシーツがくしゃくしゃになっていることに気が付いた｡そこには無意識のうちに自分の痕跡が残されていた｡この過ぎ去った時間で無意識下の自分が現れたと思う｡そもそもの本来の私はいつ頃から現れ始め、どんな姿をしていたのか、そしてこれからどんな姿になっていくのだろうか…考えが止まらない｡本来の私を探究するために、私はこのプロジェクトを始めた｡サイアノタイプを使ったのは、精密に複写できる写真の古典技法だから。カメラを介さず、最もストレートに表現できる｡撮られたのは私自身と同世代の人たちだ｡一人でネガの上に横たわると、最初は意識が鮮明に働いていたが、時間が経つにつれて、無意識の領域に入る｡そして、再び意識へと戻る。そうした時間のプロセスが痕跡としてネガに残った｡　体は現実の世界でのできことに反応する。私たちの身体はこの世界を体験し、身体の感覚シ',
			},
			{
				label: '話しているのは誰',
				id: 3,
				path: 'pic/work-pic.jpg',
				info: 'Leg<br/>Cyanotypeonwatercolorpaper<br/>(297cmx420cm)',
				description: '',
			},
			{ label: '思い思われ', id: 4, path: 'http://placekitten.com/1500/900' },
			{ label: 'Trace of Life', id: 5, path: 'https://place.dog/1500/900' },
			{ label: '暁闇', id: 6, path: 'pic/work-pic.jpg' },
		],
	},
	{
		label: 'Works',
		children: [
			{ label: 'work-11', path: '' },
			{ label: 'work-12', path: '' },
			{ label: 'work-13', path: '' },
			{ label: 'work-14', path: '' },
			{ label: 'work-15', path: '' },
			{ label: 'work-16', path: '' },
			{ label: 'work-17', path: '' },
			{ label: 'work-18', path: '' },
			{ label: 'work-19', path: '' },
			{ label: 'work-20', path: '' },
		],
	},
	{
		label: 'Exhibition',
		children: [
			{
				label: '2011',
				path: '',
				children: [
					{ label: '2011-11', path: '' },
					{ label: '2011-12', path: '' },
					{ label: '2011-13', path: '' },
					{ label: '2011-14', path: '' },
					{ label: '2011-15', path: '' },
					{ label: '2011-16', path: '' },
					{ label: '2011-17', path: '' },
					{ label: '2011-18', path: '' },
					{ label: '2011-19', path: '' },
					{ label: '2011-20', path: '' },
				],
			},
			{
				label: '2022',
				path: '',
				children: [
					{ label: '2022-11', path: '' },
					{ label: '2022-12', path: '' },
					{ label: '2022-13', path: '' },
					{ label: '2022-14', path: '' },
					{ label: '2022-15', path: '' },
					{ label: '2022-16', path: '' },
					{ label: '2022-17', path: '' },
					{ label: '2022-18', path: '' },
					{ label: '2022-19', path: '' },
					{ label: '2022-20', path: '' },
				],
			},
		],
	},
	{ label: 'Profile' },
	{ label: 'Context' },
];
