export const menuConfig = [
	{
		title: 'Portfolio',
		path: 'portfolio',
		pageType: 'catalog',
		children: [
			{ title: 'Slough', srcPath: 'pic/work-pic.jpg', pageType: 'detail' },
			{
				title: '此方',
				pageType: 'detail',
				srcPath: 'pic/work-pic.jpg',
				info: 'Leg<br/>Cyanotypeonwatercolorpaper<br/>(297cmx420cm)',
				description:
					'ある日、朝起床したら、不意にシーツがくしゃくしゃになっていることに気が付いた｡そこには無意識のうちに自分の痕跡が残されていた｡この過ぎ去った時間で無意識下の自分が現れたと思う｡そもそもの本来の私はいつ頃から現れ始め、どんな姿をしていたのか、そしてこれからどんな姿になっていくのだろうか…考えが止まらない｡本来の私を探究するために、私はこのプロジェクトを始めた｡サイアノタイプを使ったのは、精密に複写できる写真の古典技法だから。カメラを介さず、最もストレートに表現できる｡撮られたのは私自身と同世代の人たちだ｡一人でネガの上に横たわると、最初は意識が鮮明に働いていたが、時間が経つにつれて、無意識の領域に入る｡そして、再び意識へと戻る。そうした時間のプロセスが痕跡としてネガに残った｡　体は現実の世界でのできことに反応する。私たちの身体はこの世界を体験し、身体の感覚シ-----ある日、朝起床したら、不意にシーツがくしゃくしゃになっていることに気が付いた｡そこには無意識のうちに自分の痕跡が残されていた｡この過ぎ去った時間で無意識下の自分が現れたと思う｡そもそもの本来の私はいつ頃から現れ始め、どんな姿をしていたのか、そしてこれからどんな姿になっていくのだろうか…考えが止まらない｡本来の私を探究するために、私はこのプロジェクトを始めた｡サイアノタイプを使ったのは、精密に複写できる写真の古典技法だから。カメラを介さず、最もストレートに表現できる｡撮られたのは私自身と同世代の人たちだ｡一人でネガの上に横たわると、最初は意識が鮮明に働いていたが、時間が経つにつれて、無意識の領域に入る｡そして、再び意識へと戻る。そうした時間のプロセスが痕跡としてネガに残った｡　体は現実の世界でのできことに反応する。私たちの身体はこの世界を体験し、身体の感覚シ',
			},
			{
				title: '話しているのは誰',
				srcPath: 'pic/work-pic.jpg',
				pageType: 'detail',
				info: 'Leg<br/>Cyanotypeonwatercolorpaper<br/>(297cmx420cm)',
				description: '',
			},
			{ title: '思い思われ', srcPath: 'http://placekitten.com/1500/900', pageType: 'detail' },
			{ title: 'Trace of Life', srcPath: 'https://place.dog/1500/900', pageType: 'detail' },
			{ title: '暁闇', srcPath: 'pic/work-pic.jpg', pageType: 'detail' },
		],
	},
	{
		title: 'Works',
		children: [
			{ title: 'work-11', srcPath: '' },
			{ title: 'work-12', srcPath: '' },
			{ title: 'work-13', srcPath: '' },
			{ title: 'work-14', srcPath: '' },
			{ title: 'work-15', srcPath: '' },
			{ title: 'work-16', srcPath: '' },
			{ title: 'work-17', srcPath: '' },
			{ title: 'work-18', srcPath: '' },
			{ title: 'work-19', srcPath: '' },
			{ title: 'work-20', srcPath: '' },
		],
	},
	{
		title: 'Exhibition',
		children: [
			{
				title: '2011',
				path: '',
				children: [
					{ title: '2011-11', path: '' },
					{ title: '2011-12', path: '' },
					{ title: '2011-13', path: '' },
					{ title: '2011-14', path: '' },
					{ title: '2011-15', path: '' },
					{ title: '2011-16', path: '' },
					{ title: '2011-17', path: '' },
					{ title: '2011-18', path: '' },
					{ title: '2011-19', path: '' },
					{ title: '2011-20', path: '' },
				],
			},
			{
				title: '2022',
				path: '',
				children: [
					{ title: '2022-11', path: '' },
					{ title: '2022-12', path: '' },
					{ title: '2022-13', path: '' },
					{ title: '2022-14', path: '' },
					{ title: '2022-15', path: '' },
					{ title: '2022-16', path: '' },
					{ title: '2022-17', path: '' },
					{ title: '2022-18', path: '' },
					{ title: '2022-19', path: '' },
					{ title: '2022-20', path: '' },
				],
			},
		],
	},
	{ title: 'Profile' },
	{ title: 'Context' },
];
