export const worksConfig = {
	Slough: {
		title: 'Slough',
		description:
			'ある日、朝起床したら、不意にシーツがくしゃくしゃになっていることに気が付いた｡そこには無意識のうちに自分の痕跡が残されていた｡この過ぎ去った時間で無意識下の自分が現れたと思う｡そもそもの本来の私はいつ頃から現れ始め、どんな姿をしていたのか、そしてこれからどんな姿になっていくのだろうか…考えが止まらない｡本来の私を探究するために、私はこのプロジェクトを始めた｡サイアノタイプを使ったのは、精密に複写できる写真の古典技法だから。カメラを介さず、最もストレートに表現できる｡撮られたのは私自身と同世代の人たちだ｡一人でネガの上に横たわると、最初は意識が鮮明に働いていたが、時間が経つにつれて、無意識の領域に入る｡そして、再び意識へと戻る。そうした時間のプロセスが痕跡としてネガに残った｡　体は現実の世界でのできことに反応する。私たちの身体はこの世界を体験し、身体の感覚シ-----ある日、朝起床したら、不意にシーツがくしゃくしゃになっていることに気が付いた｡そこには無意識のうちに自分の痕跡が残されていた｡この過ぎ去った時間で無意識下の自分が現れたと思う｡そもそもの本来の私はいつ頃から現れ始め、どんな姿をしていたのか、そしてこれからどんな姿になっていくのだろうか…考えが止まらない｡本来の私を探究するために、私はこのプロジェクトを始めた｡サイアノタイプを使ったのは、精密に複写できる写真の古典技法だから。カメラを介さず、最もストレートに表現できる｡撮られたのは私自身と同世代の人たちだ｡一人でネガの上に横たわると、最初は意識が鮮明に働いていたが、時間が経つにつれて、無意識の領域に入る｡そして、再び意識へと戻る。そうした時間のプロセスが痕跡としてネガに残った｡　体は現実の世界でのできことに反応する。私たちの身体はこの世界を体験し、身体の感覚シ',
		max: 26,
		children: [
			{
				title: ' ',
				srcPath: 'Slough/01.jpg',
				wroks: 'Slough',
				info: 'Leg<br/>Cyanotype on watercolor paper<br/>(297cmx420cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/02.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 25min<br/>(145cm x 200cm)',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/03.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on water color paper<br/>(297cmx420cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/04.jpg',
				wroks: 'Slough',
				info: 'Back<br/>Cyanotype on watercolor paper<br/>(297cmx420cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/05.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 22min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/06.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/07.jpg',
				wroks: 'Slough',
				info: 'Leg <br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/08.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 18min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/09.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/10.jpg',
				wroks: 'Slough',
				info: 'Head<br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/11.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 15min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/12.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/13.jpg',
				wroks: 'Slough',
				info: 'Back<br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/14.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 22min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/15.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/16.jpg',
				wroks: 'Slough',
				info: 'Back<br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/17.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 25min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/18.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/19.jpg',
				wroks: 'Slough',
				info: 'Hand<br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/20.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 20min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/21.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/22.jpg',
				wroks: 'Slough',
				info: 'Back<br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/23.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 25min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/24.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/25.jpg',
				wroks: 'Slough',
				info: 'Leg<br/>Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/26.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on fabric, 17min<br/>(145cm x 200cm)',
				description: '',
				pageType: 'detail',
			},
			{
				title: ' ',
				srcPath: 'Slough/27.jpg',
				wroks: 'Slough',
				info: 'Cyanotype on watercolor paper<br/>(297mm x 420mm)',
				description: '',
				pageType: 'detail',
			},
		],
	},
};
